
apiVersion: apps/v1
kind: Deployment
metadata:
  name: output-queue
spec:
  selector:
    matchLabels:
      app: output-queue
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: output-queue
    spec:
      containers:
      - name: output-queue
        image: minio/minio:RELEASE.2020-05-01T22-19-14Z
        args:
        - server
        - /data
        env:
        - name: MINIO_ACCESS_KEY
          value: "test"
        - name: MINIO_SECRET_KEY
          value: "test@123"
        ports:
        - containerPort: 9000

---
apiVersion: v1
kind: Service
metadata:
  name: output-queue
  labels:
    service: output-queue
spec:
  selector:
    app: output-queue
  ports:
    - name: http
      port:  9000
  type: ClusterIP      

