apiVersion: apps/v1
kind: Deployment
metadata:
  name: processor
  labels:
    app: python-minio
spec:
  replicas: 1
  selector:
    matchLabels:
      app: python-minio
  template:
    metadata:
      labels:
        app: python-minio
    spec:
      containers:
        - name: python-script
          image: ggrig/jmeter-c-icap:1.0
          env:
            # Source Minio Infromation
            - name: TARGET_MINIO_URL
              value: "http://output-queue:9000"
            - name: TARGET_MINIO_ACCESS_KEY
              value: test
            - name: TARGET_MINIO_SECRET_KEY
              value: test@123
            - name: TARGET_MINIO_BUCKET
              value: output
            # Log Level (Default to Info)
            - name: LOG_LEVEL
              value: info
            - name: MY_NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: MY_POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: MY_POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: MY_POD_SERVICE_ACCOUNT
              valueFrom:
                fieldRef:
                  fieldPath: spec.serviceAccountName

