apiVersion: apps/v1
kind: Deployment
metadata:
  name: processor
  labels:
    app: python-minio
spec:
  replicas: 1
  selector:
    matchLabels:
      app: python-minio
  template:
    metadata:
      labels:
        app: python-minio
    spec:
      containers:
        - name: python-script
          image: ggrig/jmeter-c-icap:1.0
          env:
            # Source Minio Infromation
            - name: TARGET_MINIO_URL
              value: "http://output-queue:9000"
            - name: TARGET_MINIO_ACCESS_KEY
              value: test
            - name: TARGET_MINIO_SECRET_KEY
              value: test@123
            - name: TARGET_MINIO_BUCKET
              value: output
            # Log Level (Default to Info)
            - name: LOG_LEVEL
              value: info
            - name: API_TOKEN
              value: YOUR_REBUILD_API_TOKEN
            - name: API_URL
              value: "https://gzlhbtpvk2.execute-api.eu-west-1.amazonaws.com/Prod/api/rebuild/file"
                      
