name: docker_ci

on:
  push:
    paths-ignore:
    - 'upwork-devs/**'
    branches:
    - delete_me

jobs:
  tests:
    name: Build and Push jmeter docker image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        with:
          buildkitd-flags: --debug

      - name: Set up containerd
        uses: crazy-max/ghaction-setup-containerd@v1

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: src/controller/docker-jmeter-c-icap
          file: src/controller/docker-jmeter-c-icap/Dockerfile
          tags: |
            docker.pkg.github.com/${{ github.repository_owner }}/p-k8-jmeter-test-engine-v1/jmeter-icap:latest
            docker.pkg.github.com/${{ github.repository_owner }}/p-k8-jmeter-test-engine-v1/jmeter-icap:0.0.2
          outputs: type=oci,dest=/tmp/image.tar

      - name: Import image in containerd
        run: |
          sudo ctr i import --base-name docker.pkg.github.com/${{ github.repository_owner }}/p-k8-jmeter-test-engine-v1/jmeter-icap --digests --all-platforms /tmp/image.tar
      
      - name: Push image with containerd
        run: |
          sudo ctr i push --user "${{ secrets.DOCKER_USERNAME }}:${{ secrets.DOCKER_PASSWORD }}" docker.pkg.github.com/${{ github.repository_owner }}/p-k8-jmeter-test-engine-v1/jmeter-icap:latest
