name: docker_ci

on:
  push:
    paths-ignore:
    - 'upwork-devs/**'
    branches:
    - github_actions

jobs:
  tests:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to GitHub Package Container Registry
        uses: docker/login-action@v1.3.0
        with:
          registry: docker.pkg.github.com
          username: ${{ github.repository_owner }}
          password: ${{ secrets.PACKAGE_SECRET }}

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: src/controller/docker-jmeter-c-icap
          file: src/controller/docker-jmeter-c-icap/Dockerfile
          push: true
          tags: |
            docker.pkg.github.com/${{ github.repository_owner }}/p-k8-jmeter-test-engine-v1/jmeter-icap:latest
            docker.pkg.github.com/${{ github.repository_owner }}/p-k8-jmeter-test-engine-v1/jmeter-icap:0.0.1

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
