name: run_tests

on:
  push:
    paths-ignore:
    - 'upwork-devs/**'
    branches:
    - github_actions

jobs:
  tests:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: src/controller/docker-jmeter-c-icap
          file: src/controller/docker-jmeter-c-icap/Dockerfile
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/p-k8-jmeter-test-engine-v1:0.0.1
            ghcr.io/${{ github.repository_owner }}/p-k8-jmeter-test-engine-v1:latest

      - name: install kubectl
        uses: azure/setup-kubectl@v1
        with:
          version: 'latest'
        id: install_kubectl

      - uses: azure/k8s-set-context@v1
        with:
          method: service-account
          k8s-url: ${{ secrets.K8S_URL }}
          k8s-secret: ${{ secrets.K8S_SECRET }}
        id: setcontext

      - name: get_namespaces
        run: |
          kubectl get ns
